// Auto-generated by scripts/gen-namespaces.py — DO NOT EDIT
//
// Provides createNamespaces(client) factory that binds all SDK functions
// to a specific client instance for instance-based usage.
// All method signatures preserve full type safety from the generated SDK.

import type { Client } from './generated/client/index.js';
import {
  batchGetTokenPrice,
  batchQueryTokens,
  getGainerLoserList,
  getHoldTrendList,
  getHolderCount,
  getHolderDetail,
  getHolderTagCount,
  getHolders,
  getKlineCandles,
  getKlinePoints,
  getLatestListings,
  getLatestPairsQuotes,
  getLiquidityChangeList,
  getListingsInfo,
  getMemeList,
  getNetworks,
  getNewList,
  getPairsHistoricalOhlcv,
  getPairsLatestOhlcv,
  getPairsLatestTrade,
  getPlatformDetail,
  getPlatformList,
  getSecurityDetail,
  getSpotPairsLatest,
  getSwapList,
  getToken,
  getTokenPools,
  getTokenPrice,
  getTrendingList,
  getV1AltcoinSeasonIndexHistorical,
  getV1AltcoinSeasonIndexLatest,
  getV1BlockchainStatisticsLatest,
  getV1CommunityTrendingToken,
  getV1CommunityTrendingTopic,
  getV1ContentLatest,
  getV1ContentPostsComments,
  getV1ContentPostsLatest,
  getV1ContentPostsTop,
  getV1CryptocurrencyAirdrop,
  getV1CryptocurrencyAirdrops,
  getV1CryptocurrencyCategories,
  getV1CryptocurrencyCategory,
  getV1CryptocurrencyInfo,
  getV1CryptocurrencyListingsHistorical,
  getV1CryptocurrencyListingsLatest,
  getV1CryptocurrencyListingsNew,
  getV1CryptocurrencyMap,
  getV1CryptocurrencyMarketpairsLatest,
  getV1CryptocurrencyMultiplier,
  getV1CryptocurrencyOhlcvHistorical,
  getV1CryptocurrencyOhlcvLatest,
  getV1CryptocurrencyPriceperformancestatsLatest,
  getV1CryptocurrencyQuotesHistorical,
  getV1CryptocurrencyQuotesLatest,
  getV1CryptocurrencyTrendingGainerslosers,
  getV1CryptocurrencyTrendingLatest,
  getV1CryptocurrencyTrendingMostvisited,
  getV1ExchangeAssets,
  getV1ExchangeInfo,
  getV1ExchangeListingsLatest,
  getV1ExchangeMap,
  getV1ExchangeMarketpairsLatest,
  getV1ExchangeQuotesHistorical,
  getV1ExchangeQuotesLatest,
  getV1FiatMap,
  getV1GlobalmetricsQuotesHistorical,
  getV1GlobalmetricsQuotesLatest,
  getV1KeyInfo,
  getV1PartnersFlipsidecryptoFcasListingsLatest,
  getV1PartnersFlipsidecryptoFcasQuotesLatest,
  getV1SimplePrice,
  getV1ToolsPostman,
  getV1ToolsPriceconversion,
  getV2CryptocurrencyInfo,
  getV2CryptocurrencyMarketpairsLatest,
  getV2CryptocurrencyOhlcvHistorical,
  getV2CryptocurrencyOhlcvLatest,
  getV2CryptocurrencyPriceperformancestatsLatest,
  getV2CryptocurrencyQuotesHistorical,
  getV2CryptocurrencyQuotesLatest,
  getV2DexMultiplier,
  getV2SimplePrice,
  getV2ToolsPriceconversion,
  getV3CryptocurrencyListingsLatest,
  getV3CryptocurrencyQuotesHistorical,
  getV3CryptocurrencyQuotesLatest,
  getV3FearandgreedHistorical,
  getV3FearandgreedLatest,
  getV3IndexCmc100Historical,
  getV3IndexCmc100Latest,
  getV3IndexCmc20Historical,
  getV3IndexCmc20Latest,
  getV5CryptocurrencyDerivativesMarketPairsListLatest,
  getV5DerivativesLiquidationsCryptocurrencyListLatest,
  getV5DerivativesLiquidationsExchangeListLatest,
  getV5DerivativesLiquidationsQuotesLatest,
  getV5ExchangeDerivativesList,
  getV5ExchangeDerivativesMarketPairsListLatest,
  getV5RealWorldAssetsAssetsList,
  getV5RealWorldAssetsInfo,
  getV5RealWorldAssetsIssuers,
  getV5RealWorldAssetsIssuersList,
  getV5RealWorldAssetsMap,
  getV5RealWorldAssetsMarketPairsList,
  getV5RealWorldAssetsQuotesLatest,
  queryTokenLiquidity,
  search,
} from './generated/index.js';

type OmitClient<T extends (opts: any) => any> =
  Parameters<T>[0] extends undefined
    ? (opts?: never) => ReturnType<T>
    : 'client' extends keyof Parameters<T>[0]
      ? (opts: Omit<Parameters<T>[0], 'client'>) => ReturnType<T>
      : (opts: Parameters<T>[0]) => ReturnType<T>;

/**
 * Creates a namespace object with all SDK functions bound to the given client.
 * Each function is pre-configured to use the provided client instance,
 * so callers don't need to pass `{ client }` manually.
 */
export function createNamespaces(client: Client) {
  return {
    /** CMC Index */
    cmcIndex: {
      /** GET /v3/index/cmc100-historical — CoinMarketCap 100 Index Historical */
      indexCMC100Historical: ((opts: Omit<Parameters<typeof getV3IndexCmc100Historical>[0], 'client'>) => getV3IndexCmc100Historical({ ...opts, client })) as OmitClient<typeof getV3IndexCmc100Historical>,
      /** GET /v3/index/cmc100-latest — CoinMarketCap 100 Index Latest */
      indexCMC100Latest: ((opts: Omit<Parameters<typeof getV3IndexCmc100Latest>[0], 'client'>) => getV3IndexCmc100Latest({ ...opts, client })) as OmitClient<typeof getV3IndexCmc100Latest>,
      /** GET /v3/index/cmc20-historical — CoinMarketCap 20 Index Historical */
      indexCMC20Historical: ((opts: Omit<Parameters<typeof getV3IndexCmc20Historical>[0], 'client'>) => getV3IndexCmc20Historical({ ...opts, client })) as OmitClient<typeof getV3IndexCmc20Historical>,
      /** GET /v3/index/cmc20-latest — CoinMarketCap 20 Index Latest */
      indexCMC20Latest: ((opts: Omit<Parameters<typeof getV3IndexCmc20Latest>[0], 'client'>) => getV3IndexCmc20Latest({ ...opts, client })) as OmitClient<typeof getV3IndexCmc20Latest>,
    },
    /** Community */
    community: {
      /** GET /v1/community/trending/token — Community Trending Tokens */
      trendingToken: ((opts: Omit<Parameters<typeof getV1CommunityTrendingToken>[0], 'client'>) => getV1CommunityTrendingToken({ ...opts, client })) as OmitClient<typeof getV1CommunityTrendingToken>,
      /** GET /v1/community/trending/topic — Community Trending Topics */
      trendingTopic: ((opts: Omit<Parameters<typeof getV1CommunityTrendingTopic>[0], 'client'>) => getV1CommunityTrendingTopic({ ...opts, client })) as OmitClient<typeof getV1CommunityTrendingTopic>,
    },
    /** Content */
    content: {
      /** GET /v1/content/latest — Content Latest */
      latest: ((opts: Omit<Parameters<typeof getV1ContentLatest>[0], 'client'>) => getV1ContentLatest({ ...opts, client })) as OmitClient<typeof getV1ContentLatest>,
      /** GET /v1/content/posts/comments — Content Post Comments */
      postsComments: ((opts: Omit<Parameters<typeof getV1ContentPostsComments>[0], 'client'>) => getV1ContentPostsComments({ ...opts, client })) as OmitClient<typeof getV1ContentPostsComments>,
      /** GET /v1/content/posts/latest — Content Latest Posts */
      postsLatest: ((opts: Omit<Parameters<typeof getV1ContentPostsLatest>[0], 'client'>) => getV1ContentPostsLatest({ ...opts, client })) as OmitClient<typeof getV1ContentPostsLatest>,
      /** GET /v1/content/posts/top — Content Top Posts */
      postsTop: ((opts: Omit<Parameters<typeof getV1ContentPostsTop>[0], 'client'>) => getV1ContentPostsTop({ ...opts, client })) as OmitClient<typeof getV1ContentPostsTop>,
    },
    /** Crypto Others */
    cryptoOthers: {
      /** GET /v1/blockchain/statistics/latest — Statistics Latest */
      blockchainStatisticsLatest: ((opts: Omit<Parameters<typeof getV1BlockchainStatisticsLatest>[0], 'client'>) => getV1BlockchainStatisticsLatest({ ...opts, client })) as OmitClient<typeof getV1BlockchainStatisticsLatest>,
    },
    /** Cryptocurrency */
    cryptocurrency: {
      /** GET /v1/cryptocurrency/map — Cryptocurrency ID Map */
      map: ((opts: Omit<Parameters<typeof getV1CryptocurrencyMap>[0], 'client'>) => getV1CryptocurrencyMap({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyMap>,
      /** GET /v3/cryptocurrency/listings/latest — Listings Latest */
      listingsLatest: ((opts: Omit<Parameters<typeof getV3CryptocurrencyListingsLatest>[0], 'client'>) => getV3CryptocurrencyListingsLatest({ ...opts, client })) as OmitClient<typeof getV3CryptocurrencyListingsLatest>,
      /** GET /v1/cryptocurrency/listings/new — Listings New */
      listingsNew: ((opts: Omit<Parameters<typeof getV1CryptocurrencyListingsNew>[0], 'client'>) => getV1CryptocurrencyListingsNew({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyListingsNew>,
      /** GET /v1/cryptocurrency/listings/historical — Listings Historical */
      listingsHistorical: ((opts: Omit<Parameters<typeof getV1CryptocurrencyListingsHistorical>[0], 'client'>) => getV1CryptocurrencyListingsHistorical({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyListingsHistorical>,
      /** GET /v3/cryptocurrency/quotes/latest — Quotes Latest */
      quotesLatest: ((opts: Omit<Parameters<typeof getV3CryptocurrencyQuotesLatest>[0], 'client'>) => getV3CryptocurrencyQuotesLatest({ ...opts, client })) as OmitClient<typeof getV3CryptocurrencyQuotesLatest>,
      /** GET /v3/cryptocurrency/quotes/historical — Quotes Historical */
      quotesHistorical: ((opts: Omit<Parameters<typeof getV3CryptocurrencyQuotesHistorical>[0], 'client'>) => getV3CryptocurrencyQuotesHistorical({ ...opts, client })) as OmitClient<typeof getV3CryptocurrencyQuotesHistorical>,
      /** GET /v2/cryptocurrency/ohlcv/latest — OHLCV Latest */
      ohlcvLatest: ((opts: Omit<Parameters<typeof getV2CryptocurrencyOhlcvLatest>[0], 'client'>) => getV2CryptocurrencyOhlcvLatest({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyOhlcvLatest>,
      /** GET /v2/cryptocurrency/ohlcv/historical — OHLCV Historical */
      ohlcvHistorical: ((opts: Omit<Parameters<typeof getV2CryptocurrencyOhlcvHistorical>[0], 'client'>) => getV2CryptocurrencyOhlcvHistorical({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyOhlcvHistorical>,
      /** GET /v2/cryptocurrency/market-pairs/latest — Market Pairs Latest */
      marketpairsLatest: ((opts: Omit<Parameters<typeof getV2CryptocurrencyMarketpairsLatest>[0], 'client'>) => getV2CryptocurrencyMarketpairsLatest({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyMarketpairsLatest>,
      /** GET /v2/cryptocurrency/price-performance-stats/latest — Price Performance Stats */
      priceperformancestatsLatest: ((opts: Omit<Parameters<typeof getV2CryptocurrencyPriceperformancestatsLatest>[0], 'client'>) => getV2CryptocurrencyPriceperformancestatsLatest({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyPriceperformancestatsLatest>,
      /** GET /v2/cryptocurrency/info — Metadata */
      info: ((opts: Omit<Parameters<typeof getV2CryptocurrencyInfo>[0], 'client'>) => getV2CryptocurrencyInfo({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyInfo>,
      /** GET /v1/cryptocurrency/trending/latest — Trending Latest */
      trendingLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyTrendingLatest>[0], 'client'>) => getV1CryptocurrencyTrendingLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyTrendingLatest>,
      /** GET /v1/cryptocurrency/trending/gainers-losers — Trending Gainers & Losers */
      trendingGainerslosers: ((opts: Omit<Parameters<typeof getV1CryptocurrencyTrendingGainerslosers>[0], 'client'>) => getV1CryptocurrencyTrendingGainerslosers({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyTrendingGainerslosers>,
      /** GET /v1/cryptocurrency/trending/most-visited — Trending Most Visited */
      trendingMostvisited: ((opts: Omit<Parameters<typeof getV1CryptocurrencyTrendingMostvisited>[0], 'client'>) => getV1CryptocurrencyTrendingMostvisited({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyTrendingMostvisited>,
      /** GET /v2/simple/price — Simple Price */
      simplePrice: ((opts: Omit<Parameters<typeof getV2SimplePrice>[0], 'client'>) => getV2SimplePrice({ ...opts, client })) as OmitClient<typeof getV2SimplePrice>,
      /** GET /v1/cryptocurrency/categories — Categories */
      categories: ((opts: Omit<Parameters<typeof getV1CryptocurrencyCategories>[0], 'client'>) => getV1CryptocurrencyCategories({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyCategories>,
      /** GET /v1/cryptocurrency/category — Category */
      category: ((opts: Omit<Parameters<typeof getV1CryptocurrencyCategory>[0], 'client'>) => getV1CryptocurrencyCategory({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyCategory>,
      /** GET /v1/cryptocurrency/airdrops — Airdrops */
      airdrops: ((opts: Omit<Parameters<typeof getV1CryptocurrencyAirdrops>[0], 'client'>) => getV1CryptocurrencyAirdrops({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyAirdrops>,
      /** GET /v1/cryptocurrency/airdrop — Airdrop */
      airdrop: ((opts: Omit<Parameters<typeof getV1CryptocurrencyAirdrop>[0], 'client'>) => getV1CryptocurrencyAirdrop({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyAirdrop>,
    },
    /** Deprecated */
    deprecated: {
      /** GET /v1/simple/price — Simple Price v1 (deprecated) */
      simplePrice: ((opts: Omit<Parameters<typeof getV1SimplePrice>[0], 'client'>) => getV1SimplePrice({ ...opts, client })) as OmitClient<typeof getV1SimplePrice>,
      /** GET /v1/cryptocurrency/multiplier — Cryptocurrency Multiplier */
      cryptocurrencyMultiplier: ((opts: Omit<Parameters<typeof getV1CryptocurrencyMultiplier>[0], 'client'>) => getV1CryptocurrencyMultiplier({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyMultiplier>,
      /** GET /v1/cryptocurrency/info — Metadata v1 (deprecated) */
      cryptocurrencyInfo: ((opts: Omit<Parameters<typeof getV1CryptocurrencyInfo>[0], 'client'>) => getV1CryptocurrencyInfo({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyInfo>,
      /** GET /v1/tools/price-conversion — Price Conversion v1 (deprecated) */
      toolsPriceconversion: ((opts: Omit<Parameters<typeof getV1ToolsPriceconversion>[0], 'client'>) => getV1ToolsPriceconversion({ ...opts, client })) as OmitClient<typeof getV1ToolsPriceconversion>,
      /** GET /v1/cryptocurrency/listings/latest — Listings Latest v1 (deprecated) */
      cryptocurrencyListingsLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyListingsLatest>[0], 'client'>) => getV1CryptocurrencyListingsLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyListingsLatest>,
      /** GET /v1/cryptocurrency/market-pairs/latest — Market Pairs Latest v1 (deprecated) */
      cryptocurrencyMarketpairsLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyMarketpairsLatest>[0], 'client'>) => getV1CryptocurrencyMarketpairsLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyMarketpairsLatest>,
      /** GET /v1/cryptocurrency/ohlcv/historical — OHLCV Historical v1 (deprecated) */
      cryptocurrencyOhlcvHistorical: ((opts: Omit<Parameters<typeof getV1CryptocurrencyOhlcvHistorical>[0], 'client'>) => getV1CryptocurrencyOhlcvHistorical({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyOhlcvHistorical>,
      /** GET /v1/cryptocurrency/ohlcv/latest — OHLCV Latest v1 (deprecated) */
      cryptocurrencyOhlcvLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyOhlcvLatest>[0], 'client'>) => getV1CryptocurrencyOhlcvLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyOhlcvLatest>,
      /** GET /v1/cryptocurrency/price-performance-stats/latest — Price Performance Stats v1 (deprecated) */
      cryptocurrencyPriceperformancestatsLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyPriceperformancestatsLatest>[0], 'client'>) => getV1CryptocurrencyPriceperformancestatsLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyPriceperformancestatsLatest>,
      /** GET /v1/cryptocurrency/quotes/historical — Quotes Historical v1 (deprecated) */
      cryptocurrencyQuotesHistorical: ((opts: Omit<Parameters<typeof getV1CryptocurrencyQuotesHistorical>[0], 'client'>) => getV1CryptocurrencyQuotesHistorical({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyQuotesHistorical>,
      /** GET /v1/cryptocurrency/quotes/latest — Quotes Latest v1 (deprecated) */
      cryptocurrencyQuotesLatest: ((opts: Omit<Parameters<typeof getV1CryptocurrencyQuotesLatest>[0], 'client'>) => getV1CryptocurrencyQuotesLatest({ ...opts, client })) as OmitClient<typeof getV1CryptocurrencyQuotesLatest>,
      /** GET /v2/cryptocurrency/quotes/historical — Quotes Historical v2 */
      getV2CryptocurrencyQuotesHistorical: ((opts: Omit<Parameters<typeof getV2CryptocurrencyQuotesHistorical>[0], 'client'>) => getV2CryptocurrencyQuotesHistorical({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyQuotesHistorical>,
      /** GET /v2/cryptocurrency/quotes/latest — Quotes Latest v2 */
      getV2CryptocurrencyQuotesLatest: ((opts: Omit<Parameters<typeof getV2CryptocurrencyQuotesLatest>[0], 'client'>) => getV2CryptocurrencyQuotesLatest({ ...opts, client })) as OmitClient<typeof getV2CryptocurrencyQuotesLatest>,
      /** GET /v1/partners/flipside-crypto/fcas/listings/latest — FCAS Listings Latest (deprecated) */
      partnersFlipsidecryptoFcasListingsLatest: ((opts: Omit<Parameters<typeof getV1PartnersFlipsidecryptoFcasListingsLatest>[0], 'client'>) => getV1PartnersFlipsidecryptoFcasListingsLatest({ ...opts, client })) as OmitClient<typeof getV1PartnersFlipsidecryptoFcasListingsLatest>,
      /** GET /v1/partners/flipside-crypto/fcas/quotes/latest — FCAS Quotes Latest (deprecated) */
      partnersFlipsidecryptoFcasQuotesLatest: ((opts: Omit<Parameters<typeof getV1PartnersFlipsidecryptoFcasQuotesLatest>[0], 'client'>) => getV1PartnersFlipsidecryptoFcasQuotesLatest({ ...opts, client })) as OmitClient<typeof getV1PartnersFlipsidecryptoFcasQuotesLatest>,
      /** GET /v2/dex/multiplier — Get token multiplier */
      dexMultiplier: ((opts: Omit<Parameters<typeof getV2DexMultiplier>[0], 'client'>) => getV2DexMultiplier({ ...opts, client })) as OmitClient<typeof getV2DexMultiplier>,
      /** GET /v4/dex/pairs/trade/latest — Trades Latest */
      pairsLatestTrade: ((opts: Omit<Parameters<typeof getPairsLatestTrade>[0], 'client'>) => getPairsLatestTrade({ ...opts, client })) as OmitClient<typeof getPairsLatestTrade>,
      /** GET /v4/dex/pairs/ohlcv/latest — OHLCV Latest */
      pairsLatestOHLCV: ((opts: Omit<Parameters<typeof getPairsLatestOhlcv>[0], 'client'>) => getPairsLatestOhlcv({ ...opts, client })) as OmitClient<typeof getPairsLatestOhlcv>,
      /** GET /v4/dex/pairs/ohlcv/historical — OHLCV Historical */
      pairsHistoricalOHLCV: ((opts: Omit<Parameters<typeof getPairsHistoricalOhlcv>[0], 'client'>) => getPairsHistoricalOhlcv({ ...opts, client })) as OmitClient<typeof getPairsHistoricalOhlcv>,
      /** GET /v4/dex/networks/list — CoinMarketCap ID Map */
      networks: ((opts: Omit<Parameters<typeof getNetworks>[0], 'client'>) => getNetworks({ ...opts, client })) as OmitClient<typeof getNetworks>,
      /** GET /v4/dex/listings/quotes — DEX Listings Latest */
      latestListings: ((opts: Omit<Parameters<typeof getLatestListings>[0], 'client'>) => getLatestListings({ ...opts, client })) as OmitClient<typeof getLatestListings>,
      /** GET /v4/dex/listings/info — DEX Metadata */
      listingsInfo: ((opts: Omit<Parameters<typeof getListingsInfo>[0], 'client'>) => getListingsInfo({ ...opts, client })) as OmitClient<typeof getListingsInfo>,
    },
    /** Derivatives */
    derivatives: {
      /** GET /v5/exchange/derivatives/list — List derivatives exchanges */
      exchangeDerivativesList: ((opts: Omit<Parameters<typeof getV5ExchangeDerivativesList>[0], 'client'>) => getV5ExchangeDerivativesList({ ...opts, client })) as OmitClient<typeof getV5ExchangeDerivativesList>,
      /** GET /v5/exchange/derivatives/market-pairs/list/latest — Derivative market pairs by exchange */
      exchangeDerivativesMarketPairsListLatest: ((opts: Omit<Parameters<typeof getV5ExchangeDerivativesMarketPairsListLatest>[0], 'client'>) => getV5ExchangeDerivativesMarketPairsListLatest({ ...opts, client })) as OmitClient<typeof getV5ExchangeDerivativesMarketPairsListLatest>,
      /** GET /v5/cryptocurrency/derivatives/market-pairs/list/latest — Derivative market pairs by cryptocurrency */
      cryptocurrencyDerivativesMarketPairsListLatest: ((opts: Omit<Parameters<typeof getV5CryptocurrencyDerivativesMarketPairsListLatest>[0], 'client'>) => getV5CryptocurrencyDerivativesMarketPairsListLatest({ ...opts, client })) as OmitClient<typeof getV5CryptocurrencyDerivativesMarketPairsListLatest>,
      /** GET /v5/derivatives/liquidations/quotes/latest — Latest Total Liquidations */
      liquidationsQuotesLatest: ((opts: Omit<Parameters<typeof getV5DerivativesLiquidationsQuotesLatest>[0], 'client'>) => getV5DerivativesLiquidationsQuotesLatest({ ...opts, client })) as OmitClient<typeof getV5DerivativesLiquidationsQuotesLatest>,
      /** GET /v5/derivatives/liquidations/exchange/list/latest — Latest Liquidations by Exchange */
      liquidationsExchangeListLatest: ((opts: Omit<Parameters<typeof getV5DerivativesLiquidationsExchangeListLatest>[0], 'client'>) => getV5DerivativesLiquidationsExchangeListLatest({ ...opts, client })) as OmitClient<typeof getV5DerivativesLiquidationsExchangeListLatest>,
      /** GET /v5/derivatives/liquidations/cryptocurrency/list/latest — Latest Liquidations by Cryptocurrency */
      liquidationsCryptocurrencyListLatest: ((opts: Omit<Parameters<typeof getV5DerivativesLiquidationsCryptocurrencyListLatest>[0], 'client'>) => getV5DerivativesLiquidationsCryptocurrencyListLatest({ ...opts, client })) as OmitClient<typeof getV5DerivativesLiquidationsCryptocurrencyListLatest>,
    },
    /** Exchange */
    exchange: {
      /** GET /v1/exchange/map — Exchange ID Map */
      map: ((opts: Omit<Parameters<typeof getV1ExchangeMap>[0], 'client'>) => getV1ExchangeMap({ ...opts, client })) as OmitClient<typeof getV1ExchangeMap>,
      /** GET /v1/exchange/listings/latest — Listings Latest */
      listingsLatest: ((opts: Omit<Parameters<typeof getV1ExchangeListingsLatest>[0], 'client'>) => getV1ExchangeListingsLatest({ ...opts, client })) as OmitClient<typeof getV1ExchangeListingsLatest>,
      /** GET /v1/exchange/quotes/latest — Quotes Latest */
      quotesLatest: ((opts: Omit<Parameters<typeof getV1ExchangeQuotesLatest>[0], 'client'>) => getV1ExchangeQuotesLatest({ ...opts, client })) as OmitClient<typeof getV1ExchangeQuotesLatest>,
      /** GET /v1/exchange/quotes/historical — Quotes Historical */
      quotesHistorical: ((opts: Omit<Parameters<typeof getV1ExchangeQuotesHistorical>[0], 'client'>) => getV1ExchangeQuotesHistorical({ ...opts, client })) as OmitClient<typeof getV1ExchangeQuotesHistorical>,
      /** GET /v1/exchange/market-pairs/latest — Market Pairs Latest */
      marketpairsLatest: ((opts: Omit<Parameters<typeof getV1ExchangeMarketpairsLatest>[0], 'client'>) => getV1ExchangeMarketpairsLatest({ ...opts, client })) as OmitClient<typeof getV1ExchangeMarketpairsLatest>,
      /** GET /v1/exchange/assets — Exchange Assets */
      assets: ((opts: Omit<Parameters<typeof getV1ExchangeAssets>[0], 'client'>) => getV1ExchangeAssets({ ...opts, client })) as OmitClient<typeof getV1ExchangeAssets>,
      /** GET /v1/exchange/info — Metadata */
      info: ((opts: Omit<Parameters<typeof getV1ExchangeInfo>[0], 'client'>) => getV1ExchangeInfo({ ...opts, client })) as OmitClient<typeof getV1ExchangeInfo>,
    },
    /** Global Metrics */
    globalMetrics: {
      /** GET /v3/fear-and-greed/historical — CMC Crypto Fear and Greed Historical */
      fearandgreedHistorical: ((opts: Omit<Parameters<typeof getV3FearandgreedHistorical>[0], 'client'>) => getV3FearandgreedHistorical({ ...opts, client })) as OmitClient<typeof getV3FearandgreedHistorical>,
      /** GET /v3/fear-and-greed/latest — CMC Crypto Fear and Greed Latest */
      fearandgreedLatest: ((opts: Omit<Parameters<typeof getV3FearandgreedLatest>[0], 'client'>) => getV3FearandgreedLatest({ ...opts, client })) as OmitClient<typeof getV3FearandgreedLatest>,
      /** GET /v1/global-metrics/quotes/historical — Quotes Historical */
      quotesHistorical: ((opts: Omit<Parameters<typeof getV1GlobalmetricsQuotesHistorical>[0], 'client'>) => getV1GlobalmetricsQuotesHistorical({ ...opts, client })) as OmitClient<typeof getV1GlobalmetricsQuotesHistorical>,
      /** GET /v1/global-metrics/quotes/latest — Quotes Latest */
      quotesLatest: ((opts: Omit<Parameters<typeof getV1GlobalmetricsQuotesLatest>[0], 'client'>) => getV1GlobalmetricsQuotesLatest({ ...opts, client })) as OmitClient<typeof getV1GlobalmetricsQuotesLatest>,
      /** GET /v1/altcoin-season-index/latest — Altcoin Season Index Latest */
      altcoinSeasonIndexLatest: ((opts: Omit<Parameters<typeof getV1AltcoinSeasonIndexLatest>[0], 'client'>) => getV1AltcoinSeasonIndexLatest({ ...opts, client })) as OmitClient<typeof getV1AltcoinSeasonIndexLatest>,
      /** GET /v1/altcoin-season-index/historical — Altcoin Season Index Historical */
      altcoinSeasonIndexHistorical: ((opts: Omit<Parameters<typeof getV1AltcoinSeasonIndexHistorical>[0], 'client'>) => getV1AltcoinSeasonIndexHistorical({ ...opts, client })) as OmitClient<typeof getV1AltcoinSeasonIndexHistorical>,
    },
    /** Holder */
    holder: {
      /** POST /v1/dex/holders/list — Get holders list */
      holders: ((opts: Omit<Parameters<typeof getHolders>[0], 'client'>) => getHolders({ ...opts, client })) as OmitClient<typeof getHolders>,
      /** POST /v1/dex/holders/detail — Get holder detail */
      detail: ((opts: Omit<Parameters<typeof getHolderDetail>[0], 'client'>) => getHolderDetail({ ...opts, client })) as OmitClient<typeof getHolderDetail>,
      /** GET /v1/dex/holders/trend/list — Get holder trend list */
      holdTrendList: ((opts: Omit<Parameters<typeof getHoldTrendList>[0], 'client'>) => getHoldTrendList({ ...opts, client })) as OmitClient<typeof getHoldTrendList>,
      /** GET /v1/dex/holders/tag_count — Get holder tag count */
      tagCount: ((opts: Omit<Parameters<typeof getHolderTagCount>[0], 'client'>) => getHolderTagCount({ ...opts, client })) as OmitClient<typeof getHolderTagCount>,
      /** GET /v1/dex/holders/count — Get holder count */
      count: ((opts: Omit<Parameters<typeof getHolderCount>[0], 'client'>) => getHolderCount({ ...opts, client })) as OmitClient<typeof getHolderCount>,
    },
    /** OHLCV */
    ohlcv: {
      /** GET /v1/k-line/points — Get K-line points */
      klinePoints: ((opts: Omit<Parameters<typeof getKlinePoints>[0], 'client'>) => getKlinePoints({ ...opts, client })) as OmitClient<typeof getKlinePoints>,
      /** GET /v1/k-line/candles — Get K-line candles */
      klineCandles: ((opts: Omit<Parameters<typeof getKlineCandles>[0], 'client'>) => getKlineCandles({ ...opts, client })) as OmitClient<typeof getKlineCandles>,
    },
    /** Platform */
    platform: {
      /** GET /v1/dex/platform/list — Get platform list */
      list: ((opts: Omit<Parameters<typeof getPlatformList>[0], 'client'>) => getPlatformList({ ...opts, client })) as OmitClient<typeof getPlatformList>,
      /** GET /v1/dex/platform/detail — Get platform detail */
      detail: ((opts: Omit<Parameters<typeof getPlatformDetail>[0], 'client'>) => getPlatformDetail({ ...opts, client })) as OmitClient<typeof getPlatformDetail>,
    },
    /** Real World Assets */
    realWorldAssets: {
      /** GET /v5/real-world-assets/map — RWA ID Map */
      map: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsMap>[0], 'client'>) => getV5RealWorldAssetsMap({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsMap>,
      /** GET /v5/real-world-assets/info — Metadata */
      info: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsInfo>[0], 'client'>) => getV5RealWorldAssetsInfo({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsInfo>,
      /** GET /v5/real-world-assets/assets/list — RWA List */
      assetsList: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsAssetsList>[0], 'client'>) => getV5RealWorldAssetsAssetsList({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsAssetsList>,
      /** GET /v5/real-world-assets/market-pairs/list — Market Pairs */
      marketPairsList: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsMarketPairsList>[0], 'client'>) => getV5RealWorldAssetsMarketPairsList({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsMarketPairsList>,
      /** GET /v5/real-world-assets/quotes/latest — Quotes Latest */
      quotesLatest: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsQuotesLatest>[0], 'client'>) => getV5RealWorldAssetsQuotesLatest({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsQuotesLatest>,
      /** GET /v5/real-world-assets/issuers/list — Issuers List */
      issuersList: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsIssuersList>[0], 'client'>) => getV5RealWorldAssetsIssuersList({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsIssuersList>,
      /** GET /v5/real-world-assets/issuers — Issuer */
      issuers: ((opts: Omit<Parameters<typeof getV5RealWorldAssetsIssuers>[0], 'client'>) => getV5RealWorldAssetsIssuers({ ...opts, client })) as OmitClient<typeof getV5RealWorldAssetsIssuers>,
    },
    /** Token */
    token: {
      /** POST /v1/dex/tokens/trending/list — Get trending tokens */
      trendingList: ((opts: Omit<Parameters<typeof getTrendingList>[0], 'client'>) => getTrendingList({ ...opts, client })) as OmitClient<typeof getTrendingList>,
      /** POST /v1/dex/tokens/batch-query — Batch query tokens */
      batchQueryTokens: ((opts: Omit<Parameters<typeof batchQueryTokens>[0], 'client'>) => batchQueryTokens({ ...opts, client })) as OmitClient<typeof batchQueryTokens>,
      /** POST /v1/dex/token/price/batch — Batch get token prices */
      batchGetTokenPrice: ((opts: Omit<Parameters<typeof batchGetTokenPrice>[0], 'client'>) => batchGetTokenPrice({ ...opts, client })) as OmitClient<typeof batchGetTokenPrice>,
      /** POST /v1/dex/new/list — Get new tokens */
      newList: ((opts: Omit<Parameters<typeof getNewList>[0], 'client'>) => getNewList({ ...opts, client })) as OmitClient<typeof getNewList>,
      /** POST /v1/dex/meme/list — Get meme tokens */
      memeList: ((opts: Omit<Parameters<typeof getMemeList>[0], 'client'>) => getMemeList({ ...opts, client })) as OmitClient<typeof getMemeList>,
      /** POST /v1/dex/gainer-loser/list — Get top gainers and losers */
      gainerLoserList: ((opts: Omit<Parameters<typeof getGainerLoserList>[0], 'client'>) => getGainerLoserList({ ...opts, client })) as OmitClient<typeof getGainerLoserList>,
      /** GET /v4/dex/spot-pairs/latest — Pairs Listings Latest */
      spotPairsLatest: ((opts: Omit<Parameters<typeof getSpotPairsLatest>[0], 'client'>) => getSpotPairsLatest({ ...opts, client })) as OmitClient<typeof getSpotPairsLatest>,
      /** GET /v4/dex/pairs/quotes/latest — Quotes Latest */
      latestPairsQuotes: ((opts: Omit<Parameters<typeof getLatestPairsQuotes>[0], 'client'>) => getLatestPairsQuotes({ ...opts, client })) as OmitClient<typeof getLatestPairsQuotes>,
      /** GET /v1/dex/token — Get token detail */
      token: ((opts: Omit<Parameters<typeof getToken>[0], 'client'>) => getToken({ ...opts, client })) as OmitClient<typeof getToken>,
      /** GET /v1/dex/token/price — Get token price */
      price: ((opts: Omit<Parameters<typeof getTokenPrice>[0], 'client'>) => getTokenPrice({ ...opts, client })) as OmitClient<typeof getTokenPrice>,
      /** GET /v1/dex/token/pools — Get token pools */
      pools: ((opts: Omit<Parameters<typeof getTokenPools>[0], 'client'>) => getTokenPools({ ...opts, client })) as OmitClient<typeof getTokenPools>,
      /** GET /v1/dex/token-liquidity/query — Query token liquidity */
      queryTokenLiquidity: ((opts: Omit<Parameters<typeof queryTokenLiquidity>[0], 'client'>) => queryTokenLiquidity({ ...opts, client })) as OmitClient<typeof queryTokenLiquidity>,
      /** GET /v1/dex/tokens/transactions — Get swap list */
      swapList: ((opts: Omit<Parameters<typeof getSwapList>[0], 'client'>) => getSwapList({ ...opts, client })) as OmitClient<typeof getSwapList>,
      /** GET /v1/dex/security/detail — Get security detail */
      securityDetail: ((opts: Omit<Parameters<typeof getSecurityDetail>[0], 'client'>) => getSecurityDetail({ ...opts, client })) as OmitClient<typeof getSecurityDetail>,
      /** GET /v1/dex/search — Search tokens */
      search: ((opts: Omit<Parameters<typeof search>[0], 'client'>) => search({ ...opts, client })) as OmitClient<typeof search>,
      /** GET /v1/dex/liquidity-change/list — Get liquidity change list */
      liquidityChangeList: ((opts: Omit<Parameters<typeof getLiquidityChangeList>[0], 'client'>) => getLiquidityChangeList({ ...opts, client })) as OmitClient<typeof getLiquidityChangeList>,
    },
    /** Tools */
    tools: {
      /** GET /v1/fiat/map — Fiat ID Map */
      fiatMap: ((opts: Omit<Parameters<typeof getV1FiatMap>[0], 'client'>) => getV1FiatMap({ ...opts, client })) as OmitClient<typeof getV1FiatMap>,
      /** GET /v1/key/info — Key Info */
      keyInfo: ((opts: Omit<Parameters<typeof getV1KeyInfo>[0], 'client'>) => getV1KeyInfo({ ...opts, client })) as OmitClient<typeof getV1KeyInfo>,
      /** GET /v1/tools/postman — Postman Conversion v1 */
      postman: ((opts: Omit<Parameters<typeof getV1ToolsPostman>[0], 'client'>) => getV1ToolsPostman({ ...opts, client })) as OmitClient<typeof getV1ToolsPostman>,
      /** GET /v2/tools/price-conversion — Price Conversion v2 */
      priceconversion: ((opts: Omit<Parameters<typeof getV2ToolsPriceconversion>[0], 'client'>) => getV2ToolsPriceconversion({ ...opts, client })) as OmitClient<typeof getV2ToolsPriceconversion>,
    },
  } as const;
}

export type ApiNamespaces = ReturnType<typeof createNamespaces>;
